name: BUG
description: 网站有明确的错误、性能异常等
body:
  - type: markdown
    attributes:
      value: |
         

  - type: dropdown
    attributes:
      label: Type
      options:
        - 安全问题
        - 渲染问题
        - 网络问题
        - 其他问题
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug 描述
      description: 如何遇到这个bug的？请详细描述，例如您做了什么，等等。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截屏或视频
      description: 附加的截图或视频。
      placeholder: 将截图、视频直接拖拽至此处即可。
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 您确认您遇到的bug是可以复现且除您外无法发现的
      options:
        - label: 我确认
          required: true
